WSG-76-create-HIVElements-files
I-TECH-UW/who_l3_smart_tools pull request #22
Opened 2024-07-17 18:02 UTC by pmanko

2024-07-17 22:45 UTC, Pprado23 approved these changes
I don't see the actual file generated but assume that comes after

2024-07-18 10:03 UTC, xkmato requested changes

2024-07-18 10:03 UTC, xkmato commented on who_l3_smart_tools/core/cql_tools/template_generation/elements_cql_generator.py
> +elements_library_includes_template = env.from_string(
Same as comment above. This should be in a file.

2024-08-05 13:38 UTC, ibacher approved these changes

2025-02-03 04:23 UTC, merged